(ns com.xadecimal.expose-api.impl
  (:require [zprint.core :as zp]
            [clojure.string :as str]))

(def gen-warning (str/triml "
;;;; DO NOT MODIFY ;;;;
;;; WARNING ;;;

;; This class was auto-generated by expose-api, do not manually edit
;; or your edits might get overwritten when it gets re-generated.
;; Instead modify the expose-api generation.
;; Refer to https://github.com/xadecimal/expose-api

;;; WARNING ;;;
;;;; DO NOT MODIFY ;;;
"))

(defn gen-doc
  [mta]
  (when-let [doc (:doc mta)] [doc]))

(defn gen-norm-parameters
  [norm-args splice?]
  (mapv #(if splice? (symbol (str "~" %)) %) norm-args))

(defn gen-rest-parameters
  [norm-args rest-arg splice?]
  (conj
   (mapv #(if splice? (symbol (str "~" %)) %) norm-args)
   (if splice? (symbol (str "~@" rest-arg)) rest-arg)))

(defn gen-call
  [vr args macro?]
  (let [[norm-args [_ rest-arg]] (split-with (complement #{'&}) args)]
    (if (nil? rest-arg)
      (if macro?
        (cons (symbol "`") `((~(symbol vr) ~@(gen-norm-parameters norm-args true))))
        [`(~(symbol vr) ~@(gen-norm-parameters norm-args false))])
      (if macro?
        (cons (symbol "`") `((~(symbol vr) ~@(gen-rest-parameters norm-args rest-arg true))))
        [`(apply ~(symbol vr) ~@(gen-rest-parameters norm-args rest-arg false))]))))

(defn gen-macro-call
  [vr mta]
  (for [args (:arglists mta)]
    `(~args
      ~@(gen-call vr args true))))

(defn gen-macro
  [vr mta copy-meta]
  `(~'defmacro ~(:name mta)
    ~@(gen-doc mta)
    ~(select-keys mta copy-meta)
    ~@(gen-macro-call vr mta)))

(defn gen-defn
  [vr mta copy-meta]
  `(~'defn ~(:name mta)
    ~@(gen-doc mta)
    ~(assoc (select-keys mta copy-meta)
            :inline `(~'fn ~@(gen-macro-call vr mta)))
    ~@(for [args (:arglists mta)]
        `(~args
          ~@(gen-call vr args false)))))

(defn gen-str
  [forms]
  (with-out-str
    (zp/zprint forms)))

(defn gen-top-level
  [vr copy-meta]
  (gen-str
   (let [mta (meta vr)]
     (if (:macro mta)
       (gen-macro vr mta copy-meta)
       (gen-defn vr mta copy-meta)))))

(defn spit-generated-file
  [file-path ns-str top-level-forms]
  (spit file-path
        (str/join
         \newline
         (conj
          (into [gen-warning ns-str] top-level-forms)
          gen-warning))))
